# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8f2f8e144c785ec2f3e9e42628910d5ac5a54c7a69fb518ed9cae17d5d44d09716e1936c534d2ccc00adbec359998c2ab3fe30801d5bca5c98a1c697bc35b40

test:
  secret_key_base: 749974f737682172a763d4d4e8d4b2e5d0a0bff520285def5f8ecb399f821cff540b57db5443abf3acb79b7d58d247da8ef846802b7c772e2f50203a2cf990a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
